/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ladolcepizza;

import javax.swing.JOptionPane;
import BasedeDatos.Conexion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author SABAGIP
 */
public class Creacion extends javax.swing.JFrame {

    int sumaCombinacion = 0;
    int ingredentes = 0;
    int base = 0;
    int totalidaDePizzas = 0;
    int progreso = 180;
    public static int seg;
    String idCompra = "";
    float total = 0;
    float totalMultiplicado = 0;
    String nombreCliente = "";
    String apellidoPaternoCliente = "";
    String apellidoMaternoCliente = "";
    String tamaño = "";
    String tabla = "";
    ResultSet consulta;
    String comandosSQL = "";
    String Base = "";
    String tiempo = "";
    boolean activada = false;
    boolean segundoIngrediente = true, tercerIngrediente = true; // true suma, false multiplica
    boolean chocolate = false; //False = pedido sin chocolate, true = pedido con chocolate
    boolean cajeta = false;     //False = pedido sin cajeta, true = pedido con cajeta
    public static boolean bandera = false;
    PilaValorIngrediente arregloSumaCombinacion = new PilaValorIngrediente(); //Pila que mantedrá 
    pilaNombreIngredientes arregloNombreIngredientes = new pilaNombreIngredientes();
    Conexion conexion = new Conexion();
    JFrame ventana;
    Timer temp;

    /**
     * //Variables que contendrán los precios de los ingredientes
     *
     * final int PLATANO = 15, MANGO = 25, PIÑA = 17, KIWI = 10, FRESA = 25,
     * MANZANA = 16, DURAZNO = 9, HARINA = 45, GALLETA = 55;
     */
    float PLATANO = 0, MANGO = 0, PIÑA = 0, KIWI = 0, FRESA = 0,
            MANZANA = 0, DURAZNO = 0, HARINA = 0, GALLETA = 0;

    /*
     //Varibales que contendrán el valor para realizar las operaciones y cargar las
     //imagenes
     */
    final int VALOR_PLATANO = 10, VALOR_MANGO = 21, VALOR_PIÑA = 33, VALOR_KIWI = 45,
            VALOR_FRESA = 57, VALOR_MANZANA = 69, VALOR_DURAZNO = 71,
            VALOR_HARINA = 3, VALOR_GALLETA = 7;

    /**
     * Creates new form Creacion
     */
    public Creacion() {
        initComponents();

        EscalarImagen durazno = new EscalarImagen("/Imagenes/durazno.jpg", lblDurazno);
        EscalarImagen fresa = new EscalarImagen("/Imagenes/fresa.jpg", lblFresa);
        EscalarImagen kiwi = new EscalarImagen("/Imagenes/kiwi.jpg", lblKiwi);
        EscalarImagen mango = new EscalarImagen("/Imagenes/mango.jpg", lblMango);
        EscalarImagen manzana = new EscalarImagen("/Imagenes/manzana.jpg", lblManzana);
        EscalarImagen piña = new EscalarImagen("/Imagenes/piña.jpg", lblPiña);
        EscalarImagen platano = new EscalarImagen("/Imagenes/platano.jpg", lblPlatano);
        EscalarImagen harina = new EscalarImagen("/Imagenes/harina.jpg", lblHarina);
        EscalarImagen galleta = new EscalarImagen("/Imagenes/galleta.jpg", lblGalleta);
        EscalarImagen logo = new EscalarImagen("/Imagenes/logo.jpg", lblLogo);
        EscalarImagen chocolate = new EscalarImagen("/Imagenes/chocolate.jpg", lblChocolate);
        EscalarImagen cajeta = new EscalarImagen("/Imagenes/cajeta.jpg", lblCajeta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        grupoTamañosPizzas = new javax.swing.ButtonGroup();
        txtTiempo = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtIdCompra = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGalleta = new javax.swing.JLabel();
        lblHarina = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdBtnGrande = new javax.swing.JRadioButton();
        rdBtnChica = new javax.swing.JRadioButton();
        rdBtnIndividual = new javax.swing.JRadioButton();
        rdBtnMediana = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblCreacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTerminarPedido = new javax.swing.JButton();
        btnOtraFrutiPizza = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pgrProgreso = new javax.swing.JProgressBar();
        lblTemporizador = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbCantidadPizzas = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        lblMango = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPlatano = new javax.swing.JLabel();
        lblPiña = new javax.swing.JLabel();
        lblKiwi = new javax.swing.JLabel();
        lblManzana = new javax.swing.JLabel();
        lblFresa = new javax.swing.JLabel();
        lblDurazno = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblChocolate = new javax.swing.JLabel();
        lblCajeta = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FrutiPizza");
        setName(""); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNombreCliente.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 243, 138));

        lblGalleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/galleta.jpg"))); // NOI18N
        lblGalleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGalletaMouseClicked(evt);
            }
        });

        lblHarina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/harina.jpg"))); // NOI18N
        lblHarina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHarinaMouseClicked(evt);
            }
        });

        jLabel2.setText("Base");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHarina, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lblGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHarina, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(182, 244, 226));

        rdBtnGrande.setBackground(new java.awt.Color(182, 244, 226));
        grupoTamañosPizzas.add(rdBtnGrande);
        rdBtnGrande.setText("Grande");
        rdBtnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnGrandeActionPerformed(evt);
            }
        });

        rdBtnChica.setBackground(new java.awt.Color(182, 244, 226));
        grupoTamañosPizzas.add(rdBtnChica);
        rdBtnChica.setSelected(true);
        rdBtnChica.setText("Chica");
        rdBtnChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnChicaActionPerformed(evt);
            }
        });

        rdBtnIndividual.setBackground(new java.awt.Color(182, 244, 226));
        grupoTamañosPizzas.add(rdBtnIndividual);
        rdBtnIndividual.setText("Individual");
        rdBtnIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnIndividualActionPerformed(evt);
            }
        });

        rdBtnMediana.setBackground(new java.awt.Color(182, 244, 226));
        grupoTamañosPizzas.add(rdBtnMediana);
        rdBtnMediana.setText("Mediana");
        rdBtnMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMedianaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamaño");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnIndividual)
                            .addComponent(rdBtnMediana))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnGrande)
                            .addComponent(rdBtnChica)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnChica)
                    .addComponent(rdBtnIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnMediana)
                    .addComponent(rdBtnGrande))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCreacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Delicious Cream");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Total");

        btnTerminarPedido.setText("Terminar Pedido");
        btnTerminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarPedidoActionPerformed(evt);
            }
        });

        btnOtraFrutiPizza.setText("¿Otra \n Frutipizza?");
        btnOtraFrutiPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraFrutiPizzaActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("$");

        pgrProgreso.setBackground(new java.awt.Color(51, 153, 255));
        pgrProgreso.setForeground(new java.awt.Color(255, 255, 0));
        pgrProgreso.setMaximum(180);
        pgrProgreso.setValue(180);

        lblTemporizador.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTemporizador.setText("3:00");

        jLabel9.setFont(new java.awt.Font("Vijaya", 0, 36)); // NOI18N
        jLabel9.setText("Es hora de crear tu pizza");

        jPanel5.setBackground(new java.awt.Color(133, 207, 115));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Número de pizzas");

        cmbCantidadPizzas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbCantidadPizzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbCantidadPizzas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCantidadPizzasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(cmbCantidadPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cmbCantidadPizzas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel4.setBackground(new java.awt.Color(213, 64, 64));

        lblMango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mango.jpg"))); // NOI18N
        lblMango.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMangoMouseClicked(evt);
            }
        });

        jLabel4.setText("Frutas");

        lblPlatano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/platano.jpg"))); // NOI18N
        lblPlatano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlatanoMouseClicked(evt);
            }
        });

        lblPiña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piña.jpg"))); // NOI18N
        lblPiña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPiñaMouseClicked(evt);
            }
        });

        lblKiwi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kiwi.jpg"))); // NOI18N
        lblKiwi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKiwiMouseClicked(evt);
            }
        });

        lblManzana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/manzana.jpg"))); // NOI18N
        lblManzana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManzanaMouseClicked(evt);
            }
        });

        lblFresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fresa.jpg"))); // NOI18N
        lblFresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFresaMouseClicked(evt);
            }
        });

        lblDurazno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/durazno.jpg"))); // NOI18N
        lblDurazno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDuraznoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPiña, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDurazno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblMango, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKiwi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPlatano, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDurazno, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPiña, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMango, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManzana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKiwi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLogo.setText("jLabel11");

        jLabel10.setText("Complemento");

        lblChocolate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chocolate.jpg"))); // NOI18N
        lblChocolate.setText("jLabel11");
        lblChocolate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChocolateMouseClicked(evt);
            }
        });

        lblCajeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajeta.jpg"))); // NOI18N
        lblCajeta.setText("jLabel11");
        lblCajeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCajetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblCajeta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajeta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addComponent(pgrProgreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71)
                        .addComponent(lblCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnOtraFrutiPizza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTerminarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(lblTemporizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgrProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnOtraFrutiPizza)
                    .addComponent(btnTerminarPedido))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(lblNombreCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblNombreCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGalletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGalletaMouseClicked
        /**
         * Se comprueba que la pila esté vacia y se regresan las banderas de los
         * ingredientes a su valor por default para poder realizar una nueva
         * combinacion
         */
        borrarDatos();
        while (!arregloSumaCombinacion.esVacia()) {
            arregloSumaCombinacion.desapilar();
        }

        segundoIngrediente = true;
        tercerIngrediente = true;
        sumaCombinacion = 0;
        base = VALOR_GALLETA;
        Base = "galleta, ";
        tabla = tamañoTabla();

        consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"galleta\"");

        try {
            if (consulta.next()) {
                GALLETA = consulta.getFloat(1);
                total = GALLETA;
            }

        } catch (SQLException e) {

            System.out.println(e);
        }

        String path = "/Imagenes/combinaciones/" + base + ".png";
        EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
        arregloNombreIngredientes.apilar("galleta");
        lblTotal.setText("" + total);
    }//GEN-LAST:event_lblGalletaMouseClicked

    private void lblPlatanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlatanoMouseClicked
        //Si se seleccionaron mas de 3 ingredientes
        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }
        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_PLATANO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_PLATANO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"platano\"");
            try {
                if (consulta.next()) {
                    PLATANO = consulta.getFloat(1);
                    total = total + PLATANO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("platano");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }

        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_PLATANO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_PLATANO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            tercerIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"platano\"");
            try {
                if (consulta.next()) {
                    PLATANO = consulta.getFloat(1);
                    total = total + PLATANO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("platano");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }

        }
        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_PLATANO);
            sumaCombinacion = sumaCombinacion + base + VALOR_PLATANO;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"platano\"");
            try {
                if (consulta.next()) {
                    PLATANO = consulta.getFloat(1);
                    total = total + PLATANO;
                    lblTotal.setText("" + total);
                    System.out.println(total);

                    arregloNombreIngredientes.apilar("platano");
                }
            } catch (SQLException e) {

            }

        }


    }//GEN-LAST:event_lblPlatanoMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:

        borrarDatos();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void lblMangoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMangoMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        tabla = tamañoTabla();
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_MANGO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_MANGO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"mango\"");
            try {
                if (consulta.next()) {
                    MANGO = consulta.getFloat(1);
                    total = total + MANGO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("mango");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_MANGO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_MANGO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"mango\"");
            try {
                if (consulta.next()) {
                    MANGO = consulta.getFloat(1);
                    total = total + MANGO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("mango");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_MANGO);
            sumaCombinacion = sumaCombinacion + base + VALOR_MANGO;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"mango\"");
            try {
                if (consulta.next()) {
                    MANGO = consulta.getFloat(1);
                    total = total + MANGO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("mango");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }


    }//GEN-LAST:event_lblMangoMouseClicked

    private void lblPiñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPiñaMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_PIÑA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_PIÑA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"pina\"");
            try {
                if (consulta.next()) {
                    PIÑA = consulta.getFloat(1);
                    total = total + PIÑA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("pina");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_PIÑA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_PIÑA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"pina\"");
            try {
                if (consulta.next()) {
                    PIÑA = consulta.getFloat(1);
                    total = total + PIÑA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("pina");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_PIÑA);
            sumaCombinacion = sumaCombinacion + base + VALOR_PIÑA;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"pina\"");
            try {
                if (consulta.next()) {
                    PIÑA = consulta.getFloat(1);
                    total = total + PIÑA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("pina");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }


    }//GEN-LAST:event_lblPiñaMouseClicked

    private void lblKiwiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiwiMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_KIWI);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_KIWI) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"kiwi\"");
            try {
                if (consulta.next()) {
                    KIWI = consulta.getFloat(1);
                    total = total + KIWI;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("kiwi");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_KIWI);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_KIWI) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"kiwi\"");
            try {
                if (consulta.next()) {
                    KIWI = consulta.getFloat(1);
                    total = total + KIWI;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("kiwi");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_KIWI);
            sumaCombinacion = sumaCombinacion + base + VALOR_KIWI;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"kiwi\"");
            try {
                if (consulta.next()) {
                    KIWI = consulta.getFloat(1);
                    total = total + KIWI;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("kiwi");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }


    }//GEN-LAST:event_lblKiwiMouseClicked

    private void lblFresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFresaMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_FRESA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_FRESA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"fresa\"");
            try {
                if (consulta.next()) {
                    FRESA = consulta.getFloat(1);
                    total = total + FRESA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("fresa");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_FRESA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_FRESA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"fresa\"");
            try {
                if (consulta.next()) {
                    FRESA = consulta.getFloat(1);
                    total = total + FRESA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("fresa");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_FRESA);
            sumaCombinacion = sumaCombinacion + base + VALOR_FRESA;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"fresa\"");
            try {
                if (consulta.next()) {
                    FRESA = consulta.getFloat(1);
                    total = total + FRESA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("fresa");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }
    }//GEN-LAST:event_lblFresaMouseClicked

    private void lblManzanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManzanaMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_MANZANA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_MANZANA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"manzana\"");
            try {
                if (consulta.next()) {
                    MANZANA = consulta.getFloat(1);
                    total = total + MANZANA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("manzana");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_MANZANA);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_MANZANA) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"manzana\"");
            try {
                if (consulta.next()) {
                    MANZANA = consulta.getFloat(1);
                    total = total + MANZANA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("manzana");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_MANZANA);
            sumaCombinacion = sumaCombinacion + base + VALOR_MANZANA;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"manzana\"");
            try {
                if (consulta.next()) {
                    MANZANA = consulta.getFloat(1);
                    total = total + MANZANA;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("manzana");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }


    }//GEN-LAST:event_lblManzanaMouseClicked

    /**
     * El siguiente metodo implica el cambio de la cantidad de pizzas que el
     * usuario desea
     *
     * @param evt
     */
    private void cmbCantidadPizzasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCantidadPizzasItemStateChanged
        // TODO add your handling code here:    
        if (total != 0) {
            totalMultiplicado = Float.parseFloat(lblTotal.getText());

            totalMultiplicado = total * Integer.parseInt(cmbCantidadPizzas.getSelectedItem().toString());

            lblTotal.setText("" + totalMultiplicado);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero tu pizza");

        }

    }//GEN-LAST:event_cmbCantidadPizzasItemStateChanged

    private void btnOtraFrutiPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraFrutiPizzaActionPerformed
        // TODO add your handling code here:}

        tamaño = tamañoPizza();

        if (cmbCantidadPizzas.getSelectedIndex() == 0) {
            totalMultiplicado = total * Integer.parseInt(cmbCantidadPizzas.getSelectedItem().toString());
        }

        /*String sql = "INSERT INTO `frutipizza`.`compra` (`nombre_cliente`, `numero_pizzas`, `total`,`fecha_compra`) "
         + "VALUES (`" + nombreCliente + "`, " + cmbCantidadPizzas.getSelectedItem().toString() 
         + ", " + lblTotal.getText() + ", CURRENT_DATE() );";*/
        try {
            comandosSQL = "INSERT INTO detalle_compra VALUES (NULL, " + idCompra + ", \""
                    + arregloNombreIngredientes.mostrarIngredientes() + "\", "
                    + cmbCantidadPizzas.getSelectedItem().toString() + ", \" " + tamaño + " \", " + totalMultiplicado + " )";
            if (conexion.ejecutarSQL(comandosSQL)) {
                JOptionPane.showMessageDialog(rootPane, "¡Pizza agregada!");
                sumaCombinacion = 0;
                ingredentes = 0;
                base = 0;

                cmbCantidadPizzas.setSelectedIndex(0);
                borrarDatos();
            } else {
                JOptionPane.showMessageDialog(rootPane, "ERROR AL AGREGAR DETALLE_COMPRA");
                System.out.println(comandosSQL);
            }
        } catch (Exception e) {
        } finally {

        }
    }//GEN-LAST:event_btnOtraFrutiPizzaActionPerformed

    private void btnTerminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarPedidoActionPerformed
        // TODO add your handling code here:

        tamaño = tamañoPizza();

        if (cmbCantidadPizzas.getSelectedIndex() == 0) {
            totalMultiplicado = total * Integer.parseInt(cmbCantidadPizzas.getSelectedItem().toString());
        }

        comandosSQL = "INSERT INTO detalle_compra VALUES (NULL, " + idCompra + ", \""
                + arregloNombreIngredientes.mostrarIngredientes() + "\", "
                + cmbCantidadPizzas.getSelectedItem().toString() + ", \" " + tamaño + " \", " + totalMultiplicado + " )";

        if (conexion.ejecutarSQL(comandosSQL)) {
            JOptionPane.showMessageDialog(rootPane, "¡Un paso mas y terminas tu pedido!");

            /*sumaCombinacion = 0;
             ingredentes = 0;
             base = 0;*/
            TerminarPedido terminaPedido = new TerminarPedido();
            TerminarPedido.txtIdCompra.setText(idCompra + "");
            TerminarPedido.txtNombre.setText(nombreCliente);
            TerminarPedido.txtApellidoP.setText(apellidoPaternoCliente);
            TerminarPedido.txtAplellidoM.setText(apellidoMaternoCliente);
            TerminarPedido.bandera = bandera;
            int valor = pgrProgreso.getValue();
            String valor2 = valor + "";
            TerminarPedido.txtTiempo.setText(valor2);
            terminaPedido.setVisible(true);
            temp.stop();

            this.dispose();

            //borrarDatos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL AGREGAR DETALLE_COMPRA");
            System.out.println(comandosSQL);
        }


    }//GEN-LAST:event_btnTerminarPedidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:     

        nombreCliente = txtNombreCliente.getText();
        apellidoPaternoCliente = txtApellidoP.getText();
        apellidoMaternoCliente = txtApellidoM.getText();
        idCompra = txtIdCompra.getText();
        tiempo = txtTiempo.getText();

        if (idCompra.equals("") == true) {

            /**
             * Se crea la conexion a la base de datos
             */
            if (idCompra.equals("")) {

                if (conexion.crearConexion()) {
                    nombreCliente = JOptionPane.showInputDialog(rootPane, "Escribe tu nombre", "¿Quíen está ordenando?", 1);

                    if (nombreCliente == null) {
                        Inicio inicio = new Inicio();
                        inicio.setVisible(true);
                        this.dispose();
                    }
                    txtNombreCliente.setText(nombreCliente);
                    while (nombreCliente.equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Debes de escribir tu nombre para el pedido");
                        nombreCliente = JOptionPane.showInputDialog(rootPane, "Escribe tu nombre", "¿Quíen está ordenando?", 1);
                    }

                    apellidoPaternoCliente = JOptionPane.showInputDialog(rootPane, "Escribe tu apellido Paterno", "¿Quíen está ordenando?", 1);
                    txtApellidoP.setText(apellidoPaternoCliente);
                    /*while (apellidoPaternoCliente.equals("")) {
                     JOptionPane.showMessageDialog(rootPane, "Debes de escribir tu apellido paterno para el pedido");
                     apellidoPaternoCliente = JOptionPane.showInputDialog(rootPane, "Escribe tu apellido paterno", "¿Quíen está ordenando?", 1);
                     }*/

                    apellidoMaternoCliente = JOptionPane.showInputDialog(rootPane, "Escribe tu apellido materno", "¿Quíen está ordenando?", 1);
                    txtApellidoM.setText(apellidoMaternoCliente);

                    comandosSQL = "INSERT INTO compra VALUES (NULL, \"" + nombreCliente + "\", \""
                            + apellidoPaternoCliente + "\", \"" + apellidoMaternoCliente + "\", now(), 0 , 0, 0);";

                    if (conexion.ejecutarSQL(comandosSQL) == false) {
                        JOptionPane.showMessageDialog(rootPane, "Error al conectar a la Base de datos");

                        System.out.println(comandosSQL);

                        this.dispose();
                        Inicio inicio = new Inicio();
                        inicio.setVisible(true);
                    } else {
                        comandosSQL = "SELECT last_insert_id()";
                        consulta = conexion.ejecutarSQLSelect(comandosSQL);

                        try {
                            if (consulta.next()) {
                                idCompra = consulta.getString(1);
                            }
                        } catch (SQLException e) {
                            this.dispose();
                            Inicio inicio = new Inicio();
                            inicio.setVisible(true);
                        } catch (Exception e) {

                        } finally {
                            try {
                                consulta.close();
                            } catch (SQLException ex) {

                            }
                        }
                    }

                    lblNombreCliente.setText(nombreCliente + " " + apellidoPaternoCliente + " " + apellidoMaternoCliente);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al conectar a la Base de datos");

                }

            } else {
                lblNombreCliente.setText(nombreCliente + " " + apellidoPaternoCliente + " " + apellidoMaternoCliente);
                if (!conexion.crearConexion()) {
                    JOptionPane.showMessageDialog(rootPane, "Error al conectar a la base de datos, comienza de nuevo");
                    Inicio inicio = new Inicio();
                    inicio.setVisible(true);
                    this.dispose();
                }

            }

            temporizador(180, this);
            temp.start();
        } else {
            if (!conexion.crearConexion() == true) {
                JOptionPane.showMessageDialog(rootPane, "Error al conectar a la base de datos, comienza de nuevo");
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
                this.dispose();
            } else {

                temporizador(seg, this);
                temp.start();
            }
        }

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MensajeSalida mensajeSalida = new MensajeSalida();

    }//GEN-LAST:event_formWindowClosing

    private void lblHarinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHarinaMouseClicked
        /**
         * Se comprueba que la pila esté vacia y se regresan las banderas de los
         * ingredientes a su valor por default para poder realizar una nueva
         * combinacion
         */
        borrarDatos();
        while (!arregloSumaCombinacion.esVacia()) {
            arregloSumaCombinacion.desapilar();
        }
        segundoIngrediente = true;
        tercerIngrediente = true;
        sumaCombinacion = 0;
        base = VALOR_HARINA;
        Base = "harina, ";
        tabla = tamañoTabla();

        consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"harina\"");
        try {
            if (consulta.next()) {
                GALLETA = consulta.getFloat(1);
                total = GALLETA;
            }

        } catch (SQLException e) {

            System.out.println(e);
        }

        //Se carga la imagen en la pantalla
        String path = "/Imagenes/combinaciones/" + base + ".png";
        EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
        arregloNombreIngredientes.apilar("harina");
        //Se muestra el total
        lblTotal.setText("" + total);
    }//GEN-LAST:event_lblHarinaMouseClicked

    private void lblDuraznoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDuraznoMouseClicked
        // TODO add your handling code here:

        if (arregloSumaCombinacion.esLlena() == true) {
            JOptionPane.showMessageDialog(rootPane, "Solo puedes seleccionar 3 ingredientes");
        }

        //Si la pila esta vacia y no se ha seleccionado ningun ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base == 0) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona primero la base de tu pizza");
        }

        /**
         * ****************************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************EL SIGUIENTE IF ES EL DE LOS TRES
         * INGREDIENTES************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * ***********************************************************************************
         * *************************************************************************************
         */
        tabla = tamañoTabla();
        //Si ya se seleccionaron dos ingredientes y se escoge el tercero
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && tercerIngrediente == false) {
            arregloSumaCombinacion.apilar(VALOR_DURAZNO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_DURAZNO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"durazno\"");
            try {
                if (consulta.next()) {
                    DURAZNO = consulta.getFloat(1);
                    total = total + DURAZNO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("durazno");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se seleccionó un ingrediente y se seleccionó una base
        if (arregloSumaCombinacion.esVacia() == false && base != 0 && segundoIngrediente == false && tercerIngrediente == true) {
            arregloSumaCombinacion.apilar(VALOR_DURAZNO);
            sumaCombinacion = ((sumaCombinacion - base) * VALOR_DURAZNO) + base;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"durazno\"");
            try {
                if (consulta.next()) {
                    DURAZNO = consulta.getFloat(1);
                    total = total + DURAZNO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("durazno");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

        //Si ya se acaba de seleccionar un ingrediente
        if (arregloSumaCombinacion.esVacia() == true && base != 0 && segundoIngrediente) {
            arregloSumaCombinacion.apilar(VALOR_DURAZNO);
            sumaCombinacion = sumaCombinacion + base + VALOR_DURAZNO;

            String path = "/Imagenes/combinaciones/" + sumaCombinacion + ".png";
            System.out.println(path);
            EscalarImagen combinacion = new EscalarImagen(path, lblCreacion);
            segundoIngrediente = false;

            consulta = conexion.ejecutarSQLSelect("SELECT precio from ingredientes_" + tabla + " WHERE nombre = \"durazno\"");
            try {
                if (consulta.next()) {
                    DURAZNO = consulta.getFloat(1);
                    total = total + DURAZNO;
                    lblTotal.setText("" + total);

                    arregloNombreIngredientes.apilar("durazno");
                }

            } catch (SQLException e) {

                System.out.println(e);
            }
        }

    }//GEN-LAST:event_lblDuraznoMouseClicked

    private void rdBtnChicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnChicaActionPerformed
        // TODO add your handling code here:
        String cadena = "SELECT precio FROM ingredientes_chico WHERE nombre = \"";
        cambiaTamaño(cadena, 1);
    }//GEN-LAST:event_rdBtnChicaActionPerformed

    private void rdBtnIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnIndividualActionPerformed
        // TODO add your handling code here:
        String cadena = "SELECT precio FROM ingredientes_individual WHERE nombre = \"";
        cambiaTamaño(cadena, 2);


    }//GEN-LAST:event_rdBtnIndividualActionPerformed

    private void rdBtnMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMedianaActionPerformed
        // TODO add your handling code here:
        String cadena = "SELECT precio FROM ingredientes_mediano WHERE nombre = \"";
        cambiaTamaño(cadena, 3);

    }//GEN-LAST:event_rdBtnMedianaActionPerformed

    private void rdBtnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnGrandeActionPerformed
        // TODO add your handling code here:

        String cadena = "SELECT precio FROM ingredientes_grande WHERE nombre = \"";
        cambiaTamaño(cadena, 4);

    }//GEN-LAST:event_rdBtnGrandeActionPerformed

    private void lblChocolateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChocolateMouseClicked
        // TODO add your handling code here:
        chocolate = !chocolate;
        tamaño = tamañoTabla();
        float costo = 0;
        if (chocolate) {
            comandosSQL = "SELECT precio FROM ingredientes_" + tamaño + " WHERE nombre = \"chocolate\" ";
            consulta = conexion.ejecutarSQLSelect(comandosSQL);
            sumaCombinacion = sumaCombinacion + 5;
           try {
                if (consulta.next()) {
                    costo = consulta.getFloat(1);
                    if(cmbCantidadPizzas.getSelectedIndex() == 0){
                        total = total + costo;
                        lblTotal.setText(total + "");
                    }
                    else{
                        totalMultiplicado = totalMultiplicado + costo;
                        lblTotal.setText("" + totalMultiplicado);
                    }
                    
                }
            } catch (Exception e) {

            }

        } else {
            comandosSQL = "SELECT precio FROM ingredientes_" + tamaño + " WHERE nombre = \"chocolate\" ";
            consulta = conexion.ejecutarSQLSelect(comandosSQL);
            sumaCombinacion = sumaCombinacion - 5;
            try {
                if (consulta.next()) {
                    costo = consulta.getFloat(1);
                    if(cmbCantidadPizzas.getSelectedIndex() == 0){
                        total = total - costo;
                        lblTotal.setText(total + "");
                    }
                    else{
                        totalMultiplicado = totalMultiplicado - costo;
                        lblTotal.setText("" + totalMultiplicado);
                    }
                }
            } catch (Exception e) {

            }
        }
        
        EscalarImagen escalarImagen = new EscalarImagen("/Imagenes/combinaciones/" + sumaCombinacion + ".png", lblCreacion);
    }//GEN-LAST:event_lblChocolateMouseClicked

    private void lblCajetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCajetaMouseClicked
        // TODO add your handling code here:

        cajeta = !cajeta;
        tamaño = tamañoTabla();
        float costo = 0;
        if (cajeta) {
            comandosSQL = "SELECT precio FROM ingredientes_" + tamaño + " WHERE nombre = \"cajeta\" ";
            consulta = conexion.ejecutarSQLSelect(comandosSQL);

            try {
                if (consulta.next()) {
                    costo = consulta.getFloat(1);
                    if (cmbCantidadPizzas.getSelectedIndex() != 1) {
                        totalMultiplicado = totalMultiplicado + costo;
                        lblTotal.setText(totalMultiplicado + "");
                    } else {
                        total = total + costo;
                        lblTotal.setText(total + "");
                    }

                }
            } catch (Exception e) {

            }

        } else {
            comandosSQL = "SELECT precio FROM ingredientes_" + tamaño + " WHERE nombre = \"cajeta\" ";
            consulta = conexion.ejecutarSQLSelect(comandosSQL);

            try {
                if (consulta.next()) {
                    costo = consulta.getFloat(1);
                    if (cmbCantidadPizzas.getSelectedIndex() != 1) {
                        totalMultiplicado = totalMultiplicado + costo;
                        lblTotal.setText(totalMultiplicado + "");
                    } else {
                        total = total + costo;
                        lblTotal.setText(total + "");
                    }
                }
            } catch (Exception e) {

            }
        }
        EscalarImagen escalarImagen = new EscalarImagen("/Imagenes/combinaciones/" + sumaCombinacion + ".png", lblCreacion);
    }//GEN-LAST:event_lblCajetaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion().setVisible(true);
            }
        });
    }

    private void borrarDatos() {
        sumaCombinacion = 0;
        ingredentes = 0;
        base = 0;
        tamaño = "";
        Base = "";
        total = 0;
        totalMultiplicado = 0;

        segundoIngrediente = true;
        tercerIngrediente = true;
        arregloSumaCombinacion.desapilar();
        arregloSumaCombinacion.desapilar();
        arregloSumaCombinacion.desapilar();

        arregloNombreIngredientes.desapilar();
        arregloNombreIngredientes.desapilar();
        arregloNombreIngredientes.desapilar();

        lblCreacion.setIcon(null);
        lblTotal.setText("0");
        //cmbCantidadPizzas.setSelectedIndex(0);
    }

    private String tamañoPizza() {
        String tamañoPizza = "";
        if (rdBtnIndividual.isSelected()) {
            tamañoPizza = "individual";
        } else {
            if (rdBtnChica.isSelected()) {
                tamañoPizza = "chica";
            } else {
                if (rdBtnMediana.isSelected()) {
                    tamañoPizza = "mediana";
                } else {
                    tamañoPizza = "grande";
                }
            }
        }
        return tamañoPizza;
    }

    private String tamañoTabla() {
        String tamañoPizza = "";
        if (rdBtnIndividual.isSelected()) {
            tamañoPizza = "individual";
        } else {
            if (rdBtnChica.isSelected()) {
                tamañoPizza = "chico";
            } else {
                if (rdBtnMediana.isSelected()) {
                    tamañoPizza = "mediano";
                } else {
                    tamañoPizza = "grande";
                }
            }
        }
        return tamañoPizza;
    }

    void temporizador(int segundos, JFrame frame) {
        seg = segundos;
        ventana = frame;
        temp = new Timer(1000, new ActionListener() {
            float segundo;
            int minutos;

            @Override
            public void actionPerformed(ActionEvent e) {

                pgrProgreso.setValue(seg);
                minutos = seg / 60;
                segundo = (seg % 60);
                String cadena = segundo + "";
                char arreglo[] = cadena.toCharArray();
                if (arreglo.length == 3) {
                    lblTemporizador.setText(minutos + ":" + "0" + arreglo[0]);
                }
                if (arreglo.length == 4) {
                    lblTemporizador.setText(minutos + ":" + arreglo[0] + arreglo[1]);
                }

                if (seg == 0 && bandera == false) {
                    JOptionPane.showMessageDialog(rootPane, "Debes de terminar tu furipedido");
                    seg = 31;
                    bandera = true;
                    pgrProgreso.setValue(seg);
                }
                if (seg == 0 && bandera == true) {
                    JOptionPane.showMessageDialog(rootPane, "Se te ha acabado tu tiempo");
                    Inicio inicio = new Inicio();
                    inicio.setVisible(true);

                    ventana.dispose();

                }
                seg--;
            }
        });

    }

    private void cambiaTamaño(String cadena, int tamaño) {

        String ingrediente = "";
        String ingreString = "";
        float total1 = 0;
        int pos = 0;
        char arreglo[];
        String arregloIngrediente[] = new String[4];
        //Se extraen los ingredientes y se convierten en un arreglo char
        arreglo = arregloNombreIngredientes.mostrarIngredientes().toCharArray();
        //Se sacan los ingredientes del arreglo distinguiendo por comas
        for (int i = 0; i < arreglo.length; i++) {
            //Si no encuentra una coma, concatena
            if (arreglo[i] != ',') {
                ingrediente = ingrediente + arreglo[i];
                //Si la encuentras ya se concateno un ingrediente
            } else {
                arregloIngrediente[pos] = ingrediente;
                ingreString = ingrediente + "," + ingreString;
                pos++;
                ingrediente = "";
            }
            //Si ya se llegó al ultimo ingrediente, insetalo
            if (i == arreglo.length - 1) {
                ingreString = ingrediente + "," + ingreString;
                arregloIngrediente[pos] = ingrediente;
            }
        }
        //Se sacan los precios de cada ingrediente y se suman
        for (int i = 0; i < arregloIngrediente.length; i++) {
            consulta = conexion.ejecutarSQLSelect(cadena + arregloIngrediente[i] + "\"");
            try {

                if (consulta.next()) {
                    total1 = total1 + consulta.getFloat(1);
                }
            } catch (SQLException e) {
            }
        }

        total = total1;
        lblTotal.setText(total + "");
        ingrediente = "";
        arreglo = ingreString.toCharArray();
        for (int i = 0; i < arreglo.length; i++) {
            if (arreglo[i] != ',') {
                ingrediente = ingrediente + arreglo[i];
            } else {
                arregloNombreIngredientes.apilar(ingrediente);
                pos++;
                ingrediente = "";
            }
            if (i == arreglo.length - 1) {
                //arregloNombreIngredientes.apilar(ingrediente);
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnOtraFrutiPizza;
    private javax.swing.JButton btnTerminarPedido;
    private javax.swing.JComboBox cmbCantidadPizzas;
    private javax.swing.ButtonGroup grupoTamañosPizzas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCajeta;
    private javax.swing.JLabel lblChocolate;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JLabel lblDurazno;
    private javax.swing.JLabel lblFresa;
    private javax.swing.JLabel lblGalleta;
    private javax.swing.JLabel lblHarina;
    private javax.swing.JLabel lblKiwi;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMango;
    private javax.swing.JLabel lblManzana;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPiña;
    private javax.swing.JLabel lblPlatano;
    private javax.swing.JLabel lblTemporizador;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JProgressBar pgrProgreso;
    private javax.swing.JRadioButton rdBtnChica;
    private javax.swing.JRadioButton rdBtnGrande;
    private javax.swing.JRadioButton rdBtnIndividual;
    private javax.swing.JRadioButton rdBtnMediana;
    public static javax.swing.JTextField txtApellidoM;
    public static javax.swing.JTextField txtApellidoP;
    public static javax.swing.JTextField txtIdCompra;
    public static javax.swing.JTextField txtNombreCliente;
    public static javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
